### ISSUE TITLE
Issue #get_hashtag_tweets(data = ) returned rds/dataframe

### ISSUE THREAD

**Issue by Sirhurryup** [cjbarrie/academictwitteR#11]
**Describe the bug**
The execution of the get_hashtag_tweets returns a series of independent json files. Supplying a filename to the data argument returns no RDS file. I attemped with .rds and without. Does jsonlite need loading in order to access the dataframe/tibble? The read me documentation shows after authentication from the V2 API endpoint returned file results in a dataframe to view headings. 

**To Reproduce**
get_hashtag_tweets("#Blacktwitter",
                   start_tweets = "2021-01-06T00:00:00Z",
                   end_tweets =  "2021-01-13T23:59:59Z",
                   bearer_token = bear_token,
                   data_path = "Desktop/data/bti.rds")

bti <- get_hashtag_tweets("#Insurrection",
                   start_tweets = "2021-01-06T00:00:00Z",
                   end_tweets =  "2021-01-13T23:59:59Z",
                   bearer_token = bear_token,
                   data_path = "Desktop/data/bti")

**Expected behavior**
I expected a dataframe or tibble to use within the rtweet package to extract data or tidytext package. Does the json files stored in the data folder require further processing with a different package or function in the R studio environment. I even tried to save the get_hashtag_tweets in to an object. That option resulted in timeout request error. 

**Desktop (please complete the following information):**
OS: iOS Big Sur Version 11.2.2 
Browser safari Version 14.0.3

**Comment by mkalz** [comment]
I have the same problem. Specifying a .rds- file results in an error and assigning results to a data-frame results in a timeout error.

**Comment by justinchuntingho** [comment]
Due to how the codes are written, the `data_path` argument can only accept a folder name (it has to be followed by a `/`). Note that providing the path is optional, if you omit the variable, all data will be processed within the function. The option to provide a way to store the raw json file is useful if you expect your search to return a large amount of tweets or if you would like to break down your search into multiple calls. In either case, the function will return a dataframe, which you can store as an object, like this `tweets <- get_hashtag_tweets( [your arguments here] )`.

The option to store as .rds is a separate argument `file = "filename.rds"` which due with the end product. If the argument is supplied, it will save the dataframe as a .rds file (which you can read back into your R session). Again, it is useful in some cases especially when you are dealing with a lot of data.

The following codes will work:
```
get_hashtag_tweets("#Blacktwitter",
                   start_tweets = "2021-01-06T00:00:00Z",
                   end_tweets = "2021-01-13T23:59:59Z",
                   bearer_token = bear_token,
                   data_path = "data/",
                   file = "bti.rds")
```
And you would need to read back the rds into your R session for analysis:
```
bti_tweets <- readRDS("bti.rds")
```
However, the simplest way is perhaps to just store the output as an object without the above intermediate steps (if data size allows):
```
bti_tweets <- get_hashtag_tweets("#Blacktwitter",
                   start_tweets = "2021-01-06T00:00:00Z",
                   end_tweets = "2021-01-13T23:59:59Z",
                   bearer_token = bear_token)
```

**Comment by justinchuntingho** [comment]
For further development, it seems it make sense to rewrite the data_path argument to accept both a relative path or an absolute path, instead of merely a folder name.

**Comment by Sirhurryup** [comment]
@justinchuntingho The solution you provided resolves the issues when you using the file = argument with the .rds extension to capture large amounts of data. 

This package is an exceptional addition to the R programming environment. I appreciate your concise solution. 

Curious to know when you save your output using the simplest way into a R object. What is the recommended data size allotment for bypassing the intermediate steps you provided in the above example? 

When using the query argument in get_hashtag_tweets, is there an operator for the or. From the example, it appears the "+" represents the Boolean AND operator.

**Comment by mkalz** [comment]
@justinchuntingho I would like to add a question regarding memory usage. I am running a R-Studio Server on Ubuntu 18.04 on a small DigitalOcean Droplet with only 1 GB of memory and I run into memory problems with approx. 700 000 tweets.

**Comment by justinchuntingho** [comment]
Yes, there is an operator for or, it would be "#hashtag1 OR #hashtag2". Actually, in the current version, search terms separated by a space will result in the AND logic, eg "#hashtag1 #hashtag2".  See [here](https://developer.twitter.com/en/docs/twitter-api/tweets/search/integrate/build-a-query) for the full documentation.

For the data size, it all goes down to how much memory your system has (and I have not really run tests on the limits). I would probably try which ever suit myself best first, and switch to other method if it fails.

**Comment by Sirhurryup** [comment]
Perfect explanation. I review the shared materials. 

Thank you for your concise response.
