### ISSUE TITLE
Incorporate build_query into build_user_query

### ISSUE THREAD

**Issue by cjbarrie** [cjbarrie/academictwitteR#111]
Currently `get_all_tweets()` handles additional tweet parameters by passing these to `build_query()` function inside the `get_all_tweets()` function itself. 

The `get_user_tweets()` function does not behave in the same way and does not permit building additional query parameters within the function. 

This is related to #110 . Either we need to resurrect `build_user_query()` and properly incorporate it or we need to make build_query compatible with building user queries.

**Comment by chainsawriot** [comment]
Can both this and #111 be solved by adding a new parameter `users` to `build_query` and make the query parameter by default to an empty string?

```r
build_query(users = "kfc")
#+ "from:kfc"
build_query(query = "", users = c("kfc", "victoriabeckham"))
#+ c("from:kfc", "from:victoriabeckham")
```

In the end, the [`get_user_tweet`](https://github.com/cjbarrie/academictwitteR/blob/master/R/get_user_tweetsv2.R) only appends "from:" before each user handle, isn't it?

Then make `get_all_tweets` be able to handle a vector of multiple queries.

**Comment by cjbarrie** [comment]
I think the basic answer is "yes" but I remember that @justinchuntingho had some difficulties with incorporating `build_query` into `build_user_query`. This was because some of the additional parameters were not permitted when searching by user I think. 

If we can just have one `get_all_tweets` function and deprecate `get_user_tweets` I would be in favour of this. Especially as, in conversation with Suhem from Twitter, it seems that this function was confusing to some users.

**Comment by chainsawriot** [comment]
I figured that this query `from:victoriabeckham OR from:GeriHalliwell OR from:OfficialMelB OR from:EmmaBunton OR from:MelanieCmusic` works.

So, we can simply translate a `build_query(user = c("victoriabeckham", "GeriHalliwell", "OfficialMelB", "EmmaBunton", "MelanieCmusic"))` to the query above.

So that `build_query` and `build_user_query` can 2 become 1. I believe that's what the users really really want.

**Comment by cjbarrie** [comment]
Congratulations, you win Github today

**Comment by justinchuntingho** [comment]
I think that would be a preferable solution. I didn't merge them before since the original version build_query() requires a q input, but this is suboptimal since there are also other operaters that should not require a q (ie conversation_id users). I think adding a user argument would be the optimal way to go.
