### ISSUE TITLE
bind_tweets function not working

### ISSUE THREAD

**Issue by psalmuel19** [cjbarrie/academictwitteR#341]
### Please confirm the following

- [X] I have searched the existing issues
- [X] The behaviour of the program is deviated from what is described in the documentation.
- [X] I can reproduce this problem for more than one time.
- [X] This is NOT a 3-digit error -- it does not display an error message like `something went wrong. Status code: 400.`
- [ ] This is a 3-digit error and I have consulted the [Understanding API errors](https://cran.r-project.org/web/packages/academictwitteR/vignettes/academictwitteR-errors.html) vignette and the suggestions do not help.

### Describe the bug

Hi, I have used this code successfully until two days ago:
`immersive_tech <- bind_tweets('data', user = FALSE, verbose = TRUE, output_format = "tidy")`

Now I get this error:
Error in `chr_as_locations()`:
! Can't rename columns that don't exist.
✖ Column `id` doesn't exist.

I tried it on an old query for which I already have the data to check if I missed something but it failed to bind the tweets upon finishing collection. I also tried `output_format = "raw"` but the columns it returns fewer than the standard output.

Full code below:
'tweets <-
  get_all_tweets(
    query = c("virtual reality africa"),
    start_tweets = "2022-01-01T09:00:00Z",
    end_tweets = "2022-06-30T09:00:00Z",
    data_path = "data/",
    context_annotations = FALSE,
    bind_tweets = FALSE,
    n = 200
  )'

immersive_tech <- bind_tweets('data', user = FALSE, verbose = TRUE, output_format = "tidy")

### Expected Behavior

function fails to bind tweets

### Steps To Reproduce

<img width="808" alt="Screenshot 2022-07-28 at 05 46 16" src="https://user-images.githubusercontent.com/53075630/181415976-0c6d5aa9-88cd-46b8-85cb-dda0390f1ea1.png">

### Environment

Error in `chr_as_locations()`:
! Can't rename columns that don't exist.
✖ Column `id` doesn't exist.
Run `rlang::last_error()` to see where the error occurred.

**Comment by TimBMK** [comment]
As I mentioned in #304 already, the fix is simple: 
1) Go to your data directory, i.e. where you stored the tweets for collection
2) Find the .json files that lack an ID. They are named "data_.json" or "user_.json" ("user" only if you retrieved user data). These files are usually empty and are erroneously created when no data is returned for certain queries
3) Delete the files "data_.json" / "user_.json" or move them to another directory
4) Run bind_tweets on your data directory. The "tidy" format should work just fine now

We are working on fixing the issue by reorganising the data storage process. The error in the tidy format is caused by the empty files lacking the ID variable. Deleting them will not lose you any data, as they hold no information whatsoever. 

Let me know if this works

**Comment by shmuhammad2004** [comment]
@TimBMK This works for me. Thank you.
