### ISSUE TITLE
resume_collection error

### ISSUE THREAD

**Issue by astrumpf** [cjbarrie/academictwitteR#94]
I'm having issues resuming collection when the collection gets interrupted. When I try to resume the collection only 1 page is queried with no tweets returned. Oddly enough, bind_tweet_jsons works fine and returns the correct number of tweets, but the tweets themselves span the entire query from 1/1/2019 - 12/31/2019. Not sure where I'm going wrong.

![image](https://user-images.githubusercontent.com/56413137/120695775-c3ccd500-c479-11eb-968d-3f28ef974f47.png)

Here's my query:
tweets_19_20 <-
  get_all_tweets(
    tagquery,
    "2019-01-01T00:00:00Z",
    "2020-01-01T00:00:00Z",
    bearer_token,
    lang = "en",
    is_retweet = FALSE,
    is_quote = FALSE,
    file = "tweets_19_20",
    data_path = "filepath",
    bind_tweets = FALSE
  )

Here's the resume_collection statement: 
resume_collection(data_path = "filepath", bearer_token)

Note: I've substituted the actual data_path with "filepath". Any advice?

**Comment by justinchuntingho** [comment]
Status code 429 means too many requests. Can you try to install the developmental version? It should be able to put the program to sleep and resume when rate limit resets.

**Comment by astrumpf** [comment]
Just installed the developmental version - so far so good. Any idea where I went wrong with the resume_collection?

**Comment by justinchuntingho** [comment]
This is a normal function of Twitter's API to prevent people from flooding the server with requests (300 per 15 mins and 1 request per second), you will get an error when you exceed that. But it shouldn't happen since in the functions there is a 3.1 seconds sleep between calls so theoretically it will not exceed the limit (there is a chance that there were some manual calls before starting `resume_collection()` and that would add to the rate limit). Could you let me know if it happens again?

**Comment by astrumpf** [comment]
Will do, @justinchuntingho. The developmental version worked well, so i haven't had to use resume_collection(). Thanks for the help!
